name: Publish to testPyPI

on:
  workflow_dispatch:
  push:
    branches: main


jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # 这个权限是为了私有仓库。
      contents: read
      # 重要提示：这个权限对于可信发布是必需的。
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4

      - name: Publish package distributions to PyPI
        run: pdm publish --repository testpypi

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist/*
